### ISSUE TITLE
How can I run the web application?

### ISSUE THREAD

**Issue by MaxxGit** [jiwenxing/springboot-quartz#2]
Hi,
how can i run the web application? After the maven install goal I have, in the target folder, a jar file and I don't know how deploy the war for example in tomcat. Can help me?

Thank's in advance

**Comment by jiwenxing** [comment]
you can directly deploy jar file with `java -jar xxxx.jar`，if you want deploy as war without using springboot embedded tomcat, [this](https://jverson.com/spring-boot-demo/springboot_war.html) is my practice(in chinese)
maybe you should learn sth about springboot
